pipeline {
    agent any

    tools {
        // Use the JDK name you configured in Jenkins → Global Tool Configuration
        jdk 'jdk21'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/MrAbhishek01/SpringBootMVCProjects.git'
            }
        }

        stage('Build') {
            steps {
                echo "Building Spring Boot Project..."
                bat 'mvnw.cmd clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                echo "Running Tests..."
                bat 'mvnw.cmd test'
            }
        }

        stage('Package WAR/JAR') {
            steps {
                echo "Packaging Application..."
                bat 'mvnw.cmd clean package'
            }
        }

        stage('Deploy (Optional)') {
            steps {
                echo "Deploying application... (Configure your deploy logic here)"
            }
        }
    }

    post {
        success {
            echo "✔ Pipeline executed successfully!"
        }
        failure {
            echo "❌ Pipeline Failed — Check logs."
        }
    }
}
