pipeline {
    agent any

    tools {
        maven 'Maven'   // Make sure this matches your Jenkins Maven tool name
        jdk 'JDK11'     // Make sure this matches your Jenkins JDK tool name
    }

    environment {
        MAVEN_OPTS = '-Xmx1024m'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'cd Mvc_Project_07_internationalization_I18n && mvn -B -DskipTests clean package'
                    } else {
                        bat 'cd Mvc_Project_07_internationalization_I18n && mvn -B -DskipTests clean package'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'cd Mvc_Project_07_internationalization_I18n && mvn -B test'
                    } else {
                        bat 'cd Mvc_Project_07_internationalization_I18n && mvn -B test'
                    }
                }
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'Mvc_Project_07_internationalization_I18n/target/*.jar, Mvc_Project_07_internationalization_I18n/target/*.war', allowEmptyArchive: true
            }
        }

        stage('Publish Test Results') {
            steps {
                junit allowEmptyResults: true, testResults: 'Mvc_Project_07_internationalization_I18n/target/surefire-reports/*.xml'
            }
        }
    }

    post {
        success {
            echo 'Build finished: SUCCESS'
        }
        unstable {
            echo 'Build finished: UNSTABLE'
        }
        failure {
            echo 'Build finished: FAILURE'
        }
        always {
            cleanWs()
        }
    }
}
